<?php

// autoload.php @generated by Composer
require  __DIR__ . ' /vendor/autoload.php ' ;

use  Spipu \ Html2Pdf \ Html2Pdf ;

$html2pdf =  new  Html2Pdf (); 
$html2pdf -> writeHTML ( ' <h1> HelloWorld </h1> Ceci est mon premier test ' ); 
$html2pdf -> output ();
