-- MySQL Script generated by MySQL Workbench
-- Sat Nov 24 12:58:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_facturation
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_facturation` ;

-- -----------------------------------------------------
-- Schema db_facturation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_facturation` DEFAULT CHARACTER SET utf8 ;
USE `db_facturation` ;

-- -----------------------------------------------------
-- Table `db_facturation`.`t_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_facturation`.`t_client` ;

CREATE TABLE IF NOT EXISTS `db_facturation`.`t_client` (
  `lg_CLIENT_ID` VARCHAR(20) NOT NULL,
  `str_NAME` VARCHAR(45) NULL,
  `str_STATUT` varchar(45) DEFAULT NULL,
  `str_CREATED_BY` varchar(45) DEFAULT NULL,
  `dt_CREATED` datetime DEFAULT NULL,
  `str_UPDATED_BY` varchar(45) DEFAULT NULL,
  `dt_UPDATED` datetime DEFAULT NULL,
  PRIMARY KEY (`lg_CLIENT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_facturation`.`t_branche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_facturation`.`t_branche` ;

CREATE TABLE IF NOT EXISTS `db_facturation`.`t_branche` (
  `lg_BRANCHE_ID` VARCHAR(20) NOT NULL,
  `str_WORDING` VARCHAR(45) NULL,
  `str_STATUT` varchar(45) DEFAULT NULL,
  `str_CREATED_BY` varchar(45) DEFAULT NULL,
  `dt_CREATED` datetime DEFAULT NULL,
  `str_UPDATED_BY` varchar(45) DEFAULT NULL,
  `dt_UPDATED` datetime DEFAULT NULL,
  PRIMARY KEY (`lg_BRANCHE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_facturation`.`t_facture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_facturation`.`t_facture` ;

CREATE TABLE IF NOT EXISTS `db_facturation`.`t_facture` (
  `lg_FACTURE_ID` VARCHAR(20) NOT NULL,
  `int_NUMFACT` INT NULL,
  `str_POLICE` VARCHAR(15) NULL,
  `dt_DATE` DATE NULL,
  `dt_EFFET` DATE NULL,
  `dt_ECHEANCE` DATE NULL,
  `int_PRIME_TTC` INT NULL,
  `int_TAXE` INT NULL,
  `int_PRIME_NETTE` INT NULL,
  `str_STATUT` varchar(45) DEFAULT NULL,
  `str_CREATED_BY` varchar(45) DEFAULT NULL,
  `dt_CREATED` datetime DEFAULT NULL,
  `str_UPDATED_BY` varchar(45) DEFAULT NULL,
  `dt_UPDATED` datetime DEFAULT NULL,
  `lg_CLIENT_ID` VARCHAR(20) NULL,
  `lg_BRANCHE_ID` VARCHAR(20) NULL,
  PRIMARY KEY (`lg_FACTURE_ID`),
  INDEX `fk_t_facture_t_client1_idx` (`lg_CLIENT_ID` ASC) ,
  INDEX `fk_t_facture_t_branche1_idx` (`lg_BRANCHE_ID` ASC) ,
  CONSTRAINT `fk_t_facture_t_client1`
    FOREIGN KEY (`lg_CLIENT_ID`)
    REFERENCES `db_facturation`.`t_client` (`lg_CLIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_facture_t_branche1`
    FOREIGN KEY (`lg_BRANCHE_ID`)
    REFERENCES `db_facturation`.`t_branche` (`lg_BRANCHE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
